version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  app:
    build: .
    depends_on:
      - redis
      - mailhog
    environment:
      - REDIS_HOST=redis
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SMTP_SENDER=anything@example.com
    volumes:
      - .:/app
    command: python producer.py
  worker:
    build: .
    depends_on:
      - redis
      - mailhog
    environment:
      - REDIS_HOST=redis
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - SMTP_SENDER=anything@example.com
    volumes:
      - .:/app
    command: python worker.py
