version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    command: python producer.py
  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    command: python worker.py
